# Random numbers generation in Python
The Python standard library provides a module called random that offers a suite of functions for generating random numbers.

Python uses a popular and robust pseudorandom number generator called the Mersenne Twister.

The generator produces a __deterministic sequence__ which has some interesting properties
- it the sequence is _very long_, at the end of the sequence the generator repeats the same sequence
- if you consider a portion of the sequence which is significantly shorther than the length of the full sequence it looks like a random sequence
    - i.e. several statistical procedures answer positively to a randomness test
- you can choose the starting point of the sequence setting the __seed__, which an integer number
- the base generator produces integer, but any other kind of data can be generated with appropriate transformation functions
- the base distribution is __uniform__, but any other distribution can be generated with appropriate transformation functions
- the base libraries always provide a wide set of functions to deal with data types and probability distributions

## The `random` library
A few examples

In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 10 19:00:16 2019

@author: csartori
"""


from random import seed, random, randint\
                 , uniform, expovariate, randrange\
                 , choice, shuffle, sample
random_seed = 42
# seed random number generator

Observation: in `print` the `end` parameter prevents newline after each printing

In [5]:
seed(random_seed)
for x in range(10):
  print(randint(1,101), end = " ") # random integers between 1 and 100
# first sequence

82 15 4 95 36 32 29 18 95 14 

In [30]:
for x in range(10):
  print(randint(1,101), end = " ") # random integers between 1 and 100
# this is a new sequence

87 95 70 12 76 55 5 4 12 28 

In [31]:
seed(random_seed)
for x in range(10):
  print(randint(1,101), end = " ") # random integers between 1 and 100
# the seed is reset, therefore the sequence is the same as the first one

82 15 4 95 36 32 29 18 95 14 

In [21]:
random()                             # Random float:  0.0 <= x < 1.0

0.6766994874229113

In [39]:
random.uniform(2.5, 10.0)                   # Random float:  2.5 <= x < 10.0

6.133937873964126

In [40]:
random.expovariate(1 / 5)                   # Interval between arrivals averaging 5 seconds

2.1810440994162397

In [41]:
random.randrange(10)                        # Integer from 0 to 9 inclusive

2

In [42]:
random.randrange(0, 101, 2)                 # Even integer from 0 to 100 inclusive

32

In [43]:
random.choice(['win', 'lose', 'draw'])      # Single random element from a sequence

'win'

In [44]:
deck = 'ace two three four'.split()
random.shuffle(deck)                        # Shuffle a list
deck

['three', 'four', 'two', 'ace']

In [45]:
random.sample([10, 20, 30, 40, 50], k=4)    # Four samples without replacement

[40, 10, 20, 30]

## The `numpy.random` library
A few examples

In [16]:
import numpy.random as npr
random_seed = 42

In [20]:
npr.seed(random_seed)
print(npr.randint(100, size = 10)) # random integers between 1 and 100
# first sequence

[51 92 14 71 60 20 82 86 74 74]


In [21]:
print(npr.randint(100, size = 10)) # random integers between 1 and 100
# new sequence

[87 99 23  2 21 52  1 87 29 37]


In [22]:
npr.seed(random_seed)
print(npr.randint(100, size = 10)) # random integers between 1 and 100
# first sequence again

[51 92 14 71 60 20 82 86 74 74]


In [25]:
np.random.choice(5, 20, p=[0.05, 0.1, 0.3, 0.5, 0.05])

array([1, 3, 2, 1, 3, 0, 3, 2, 3, 2, 3, 3, 2, 4, 3, 3, 3, 3, 3, 1])

## Comparison of speed

In [17]:
N = 1000000

Generaton of `N` values

The `%timeit` __magic function__ computes the time necessary to execute a statement, averaging repeated runs

In [18]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

531 ms ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%timeit npr.normal(size=N)

20.1 ms ± 714 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
